$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: sklearn-deployment
endpoint_name: diabetes
model:
  name: mir-sample-sklearn-ncd-model
  version: 1
  path: sk-diabetes-model/model
  type: mlflow_model
instance_type: Standard_DS3_v2
instance_count: 1