name: Manually trigger an Azure Machine Learning job

on:
  push:
    branches:
      - main
  
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    # - name: Azure CLI script
    #   uses: azure/CLI@v1
    #   with:
    #     azcliversion: 2.0.72
    #     inlineScript: |
    #       az account show
    #       az storage -h
    - name: Run training job for test on 09-07
      run: az ml job create --file src/job.yml --resource-group reva_mlops --workspace-name ws_ml
    - name: install flak8
      run: |
        python -m pip install flake8
    - name: lint code with flake8
      run: |
          flake8 src/model/train.py
    - name: install pytest
      run: |
            python install pytest
    - name: unit test using pytest
      run: |
          pytest tests/


