name: dev-prod-job

on:
  push:
    branches: [ main ]
  
jobs:
  # lint-and-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up Python
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: '3.8'
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt
  #     - name: install flake8
  #       run: |
  #         python -m pip install flake8
  #     - name: lint code with flake8
  #       run: |
  #         flake8 src/model/train.py
  #     - name: Run tests with pytest
  #       run: pytest tests/

  experiment:
    runs-on: ubuntu-latest
    # needs: lint-and-test
    environment:
        name: dev
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Use Python version 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: install pytest and requirements.txt
      run: |
        python -m pip install -r requirements.txt
    # - name: unit test using pytest
    #   run: |
    #     pytest tests/
    - name: List files in the development data directory
      run: ls -la experimentation
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Run training job for dev
      run: |
        az ml job create --file src/job.yml --resource-group reva_mlops_dev_rg --workspace-name ws_ml_dev --stream
        az ml model create --name "sk-diabetes-model" --version 1 --path azureml://jobs/$RUN_ID/outputs/artifacts/$MODEL_PATH --resource-group reva_mlops_dev_rg --workspace-name ws_ml_dev
    # - name: register model in dev      
    #   run: |
    #     $MODEL_NAME
    #     $RUN_ID
    #     $MODEL_PATH  
    #     az ml model create --name $MODEL_NAME --version 1 --path azureml://jobs/$RUN_ID/outputs/artifacts/$MODEL_PATH --resource-group reva_mlops_dev_rg --workspace-name ws_ml_dev
  

  production:
    runs-on: ubuntu-latest
    needs: experiment
    environment:
        name: prd
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Use Python version 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: install dependencies & requirements.txt
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: List files in the production data directory
      run: ls -la production
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Run training job for prod
      run: az ml job create --file src/job-prd.yml --resource-group reva_mlops_prd_rg --workspace-name ws_ml_prd --stream


